application: 'winter-rider-656'
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /menu
  static_files: menu.html
  upload: menu.html
- url: /css
  static_dir: css
- url: /owl-carousel
  static_dir: owl-carousel
- url: /img
  static_dir: img
- url: /bliss_delivery
  script: bliss_delivery.app
- url: /catering
  static_files: catering.html
  upload: catering.html
- url: /contact
  static_files: contact.html
  upload: contact.html
- url: /about
  static_files: about.html
  upload: about.html

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: ssl
  version: latest
